### ISSUE TITLE
Robustness 

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/IOPv5#14]
Alex Giladi has introduced the `@robustness` attribute in DASH 5th edition. Now in clause 4.2, it says  "However, the required robustness level may be different for different device types and is not expressed in the MPD." It would be preferred to add this functionality for robustness signaling and explain how to use it instead of ignoring it.

**Comment by ZmGorynych** [comment]
See proposed text in #18

**Comment by lpiron** [comment]
Text has been added under section 7.3.
