### ISSUE TITLE
Relation to CMAF Profile for DASH content

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/IOPv5#16]
The 5th edition of DASH defines the DASH profile that we use in the 5th edition. It is particularly mentioned:

If the content in an Adaptation Set is protected, the following applies:
  - the requirements in clause 8 of ISO/IEC 23000-19 clause “Common Encryption of CMAF tracks” shall apply,
  - the `ContentProtection` element shall be present and set as follows:
     - A `ContentProtection` element with `@schemeIdUri` equal to `"urn:mpeg:dash:mp4protection:2011"` and `@value` equal to an encryption scheme defined in ISO/IEC 23001-7. It may contain a `@cenc:default_KID` attribute. If present, the value of this attribute shall match the `'tenc'` box `default_KID` value.
    -  At least one `ContentProtection` element with `@schemeIdUri` equal to a UUID value that signals that content keys can be obtained with a DRM system identified by the UUID. It may contain a `@cenc:default_KID` attribute and a `cenc:pssh` element. If present, the values shall match the tenc box `default_KID` value and the `moov` box pssh value respectively.

**Comment by lpiron** [comment]
IOP mandates the presence of @cenc:default_KID for the schemeIdUri equal to "urn:mpeg:dash:mp4protection:2011" since version 4.2

**Comment by lpiron** [comment]
Closing as we are aligned with this text in section 7.2 and 7.3.
