### ISSUE TITLE
Usage of SHOULD

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/IOPv5#19]
I found 19 instances with SHOULD included. SHOULDs are difficult, because a client always needs to implement the exception that the should is not implemented. I believe it would be good to check each of those, if
1) can it be changed to a SHALL
2) if not, can it be formulated differently
3) what does it mean for the implementor if the should is not the case and possibly add a NOTE explaining why this is not a shall and what is the case if this rule is not implemented.

**Comment by lpiron** [comment]
Some SHOULD changed in SHALL. Some sentences removed as these were not bringing any value. Remaining SHOULD (11 instances) are meant to be SHOULD.

**Comment by lpiron** [comment]
Closing
