### ISSUE TITLE
Part 6 - Section 8 : Namespace does not align with what is shown in Annex A

### ISSUE THREAD

**Issue by dsilhavy** [Dash-Industry-Forum/IOPv5#27]
In the example in Section 8 the namespace is defined as `xmlns:dashif="https://dashif.org/">`. Should this be aligned with what is shown in Annex A `xmlns:dashif="https://dashif.org/CPS" ` ?

**Comment by mikedo** [comment]
Yes

**Comment by lpiron** [comment]
Corrected
