### ISSUE TITLE
Part 6 - Section 10 : Addition of "https is required for EME support"

### ISSUE THREAD

**Issue by dsilhavy** [Dash-Industry-Forum/IOPv5#28]
This is a suggestion for Section 10 "HTTPS and DASH": It might be worth mentioning that browsers like Chrome require the usage of https for EME support. Applications delivered via http will not be able to use the EME. 

The corresponding error message in dash.js:
`No supported version of EME detected on this user agent! - Attempts to play encrypted content will fail! `

**Comment by lpiron** [comment]
This added as a note in section 10.
