### ISSUE TITLE
part 6 (editorial): improve DASH-IF System registry references and explanation

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/IOPv5#7]
DASH-IF system-specific identifier registry is mentioned once but 
an explicit refernence is missing, clause 4 mentions 
https://dashif.org/identifiers/content_protection/. 
I think this should probably also be added to the reference list and referenced explitly throughout the document.

Other questions that may be good to explain are: what is the status of this registry ? 
Explicit text on the status and usage of the registry. As the registry is defined by DASH-IF 
I think it should be described.
Is this registry something that only applies to DASH or is it more generic ? 
How did DASH-IF end up defining this list what are procedures to update/amend. 

This kind of information may help readers without background knowledge on this.

**Comment by lpiron** [comment]
For adding the URL in the reference list. As far as I remember,this is not possible under the ETSI editing rules. As we aim at sending IOP v5 to ETSI, if we add this URL in the reference list, this will be removed by ETSI.
I agree that it would be good to add some text on the status of this registry. As there are other registries maintained by DASH-IF, I would prefer to see some text added in part 1 under, for example, section 5.4 that presents all DASH-IF specifications and guidelines, or maybe this deserves its own section in part 1.

**Comment by RufaelDev** [comment]
Yes this is reaonable, a mention that they are actively maintained on the DASH-IF website, and criteria and procedures how these can be updated and contributed to would be good to mention, this can then be referenced in this part, thanks!

**Comment by lpiron** [comment]
Closing as Part 1 includes a section on identifiers
