### ISSUE TITLE
PART 6: Support for an Optional attribute in Authzurl

### ISSUE THREAD

**Issue by yotta-raj** [Dash-Industry-Forum/IOPv5#8]
In section 7.3 

> Multiple dashif:Laurl or dashif:Authzurl elements under the same ContentProtection descriptor define sets of equivalent alternatives for the DASH client to choose from. A DASH client should select a random item from the set every time the value of such an element is used if the attributes of the elements have the same values.

In order to determine which Authzurl may be appropriately be used some further information is required similar to the dashid:Laurl where `licenseType` has been added. 

Therefore I propose that `authzType` optional attribute is added so that multiple Laurl's can match with multiple Authzurl.

**Comment by lpiron** [comment]
Will be added in the revision of the document

**Comment by lpiron** [comment]
Document updated
