### ISSUE TITLE
PART 6: Add a licenseType example in Section 7.4

### ISSUE THREAD

**Issue by yotta-raj** [Dash-Industry-Forum/IOPv5#9]
In Section 7 provides an example of contentId. 

`
<ContentProtection schemeIdUri="urn:uuid:d0ee2730-09b5-459f-8452-200e52b37567" value="AcmeDRM 2.0">
 <cenc:pssh>YmFzZTY0IGVuY29kZWQgY29udGVudHMgb2YgkXBzc2iSIGJveCB3aXRoIHRoaXMgU3lzdGVtSUQ= 
      </cenc:pssh>
`

`<dashif:Authzurl> https://example.com/tenants/5341/authorize?contentId=movie865343651</dashif:Authzurl>`

`<dashif:Laurl>https://example.com/moviecatalog-license-api/movie865343651/AcquireLicense </dashif:Laurl>`

`
</ContentProtection>
`

In the ATSC 3.0 market we use licenseType to provide some information about content ID. I would like this alternative to be added to show that this model may also be valid. 

`<dashif:Laurl licenseType=”contentId-1.0”>file://contentid/movie865343651</dashif:Laurl>  
`

**Comment by lpiron** [comment]
Document updated with the proposed resolution
